version: "3.9"
services:
  backend-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    env_file:
      - .env.docker
    ports:
      - 4000:4000
      - 8000:8000
    depends_on:
      - azurite
